import java.util.ArrayList;
import java.util.Date;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class DataStore {

    static Connection con = null;
    static Statement stmt = null;

    DataStore() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/calendar", "root", "root");
            stmt = con.createStatement();

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public static void main(String args[]) {

        DataStore db = new DataStore();
        db.fetch(new Date());
        try {
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    void add(String text, Date date) {
        try {
            PreparedStatement pstmt = con.prepareStatement("insert into events (edesc, edate) " + " values (?, ?)");
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            pstmt.setString(1, text);
            pstmt.setDate(2, sqlDate);
            pstmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    void delete(Event event) {
        try {
            PreparedStatement pstmt = con.prepareStatement("delete from events where eid=(?)");
            pstmt.setInt(1, event.id);
            pstmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    ArrayList<Event> fetch(Date date) {
        ArrayList<Event> events = new ArrayList<Event>();
        try {
            PreparedStatement pstmt = con.prepareStatement("select * from events where edate=(?)");
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            pstmt.setDate(1, sqlDate);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next())
                events.add(new Event(rs.getInt(1), rs.getDate(2), rs.getString(3)));
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return events;
    }
}

class Event {
    int id;
    Date date;
    String event_description;

    Event(int i, Date d, String e) {
        date = d;
        event_description = e;
        id = i;
    }

    Event() {

    }
}

class DataStoreBak {
    ArrayList<Event> events = new ArrayList<Event>();

    DataStoreBak() {
        for (int i = 0; i < 10; i++) {
            events.add(new Event(i, new Date(), "aaaaaaaaaaaaaaaa" + String.valueOf(i)));
        }
    }

    void add(String text, Date date) {
        // substitute id for one generated by db
        events.add(new Event(5, date, text));
    }

    void delete(Event event) {
        events.remove(event);
    }

    ArrayList<Event> fetch(Date date) {
        return events;
    }
}
