import java.util.ArrayList;
import java.util.Date;

class Event {
    int id;
    Date date;
    String event_description;

    Event(int i, Date d, String e) {
        date = d;
        event_description = e;
        id = i;
    }

    Event() {

    }
}

public class DataStore {
    ArrayList<Event> events = new ArrayList<Event>();

    DataStore() {
        for (int i = 0; i < 10; i++) {
            events.add(new Event(i, new Date(), "aaaaaaaaaaaaaaaa" + String.valueOf(i)));
        }
    }

    void add(String text, Date date) {
        // substitute id for one generated by db
        events.add(new Event(5, date, text));
    }

    void delete(Event event) {
        events.remove(event);
    }

    ArrayList<Event> fetch(Date date) {
        return events;
    }
}